### ISSUE TITLE
During a retro, players log their ZPD / stretchiness for the project

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/game-cli#19]
As a part of the retrospective, players should be determining the difficulty / stretchiness of the project.

Possible interface:

```
> /log -r -q7 1.2
```

Where the argument is the _experienced difficulty_, a float in the range `-1..2` inclusive, corresponding to the following semantic markers: 

```
-1: bored
0: comfortable
1: challenged (i.e. ZPD sweet spot)
2: overwhelmed
```

**Comment by jeffreywescott** [comment]
This is probably not a `game-cli` issue since we're not using `/log` anymore. It probably belongs in the `game` repo ...

**Comment by tannerwelsh** [comment]
Roger, moving to game...

**Comment by tannerwelsh** [comment]
Issue moved to [LearnersGuild/game #384](https://github.com/LearnersGuild/game/issues/384) via [**ZenHub**](https://www.zenhub.com/)
