### ISSUE TITLE
Add handling for `/stats` command

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/game-cli#21]
## Use Cases

- `/stats`: show stats overview
- `/stats STAT_NAME`: show detail view for a particular stat
- `/stats --help`: print help on the stats command, _including_ the list of available `STAT_NAME` arguments that will work.

**Comment by tannerwelsh** [comment]
Specs defined in https://github.com/LearnersGuild/learning-os-software/pull/135

**Comment by jeffreywescott** [comment]
@tannerwelsh -- please update this once you figure out the behavior around viewing stats. Thanks!

**Comment by tannerwelsh** [comment]
Thanks @jeffreywescott. This is now blocked by https://github.com/LearnersGuild/game-prototype/issues/109

**Comment by jeffreywescott** [comment]
Admin UI to the rescue!
