### ISSUE TITLE
Players can review projects using the `/review` command.

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/game-cli#27]
Completeness and quality are both percent scores between 0-100. Value passed can be a decimal, but will be rounded to the hundreds place after entering.

- `/review #project-id --completeness 89 --quality 63.1`: review both completeness and quality in one command
- `/review #project-id -c28.2 -q63.1`: review both completeness and quality, using short-form options
- `/review #project-id --completeness 89`: review just completeness
- `/review #project-id -q 63.1`: review just quality
- `/review #project-id`: display the user's current review for this project, with `N/A` as placeholders for missing completeness / quality values

## Example Usage & Errors

```
@learner  > /review #silly-slug
@echo     > Project #silly-slug has 4 reviews. You have not reviewed project #silly-slug.

            To review this project, analyze their artifact:
            > http://link.to.artifact/

            Use the rubric provided to calculate and submit a `--completeness` and `--quality` score.
@learner  > /review #silly-slug --completeness 89
@echo     > Completeness score captured for #silly-slug! Review is not yet complete.
@learner  > /project list --in-review
@echo     > You have reviewed 2/5 projects this cycle. Nice work!

               Project                  C    Q    Artifact
            X  #terrible-tiger          63   42   https://github.com/owner/repo
            X  #anxious-aardvark        19   77   https://github.com/owner/repo
            -  #silly-slug              89        https://github.com/owner/repo
            -  #fantastic-falcon                  https://github.com/owner/repo
            -  #creepy-caterpillar                https://github.com/owner/repo
@learner  > /review --quality 103
@echo     > Error: missing project id.

            When reviewing a project, be sure to include its id (for example, #bitter-bunny-2).

            Use `/review --help` to read the docs.

@learner  > /review #silly-slug --quality 103
@echo     > Error: invalid quality score.

            Quality scores must be between 1 and 100 inclusive. Decimals up to the hundreds place are allowed.

            Use `/review --help` to read the docs.

@learner  > /review #silly-slug --quality 72
@echo     > Quality score captured for #silly-slug. Review is complete. Thank you for your input.
@learner  > /review #fantastic-falcon -c75.3 -q80.8
@echo     > Completeness and quality scores captured for #fantastic-falcon! Review is complete. Thank you for your input.
```

---
originated from https://github.com/LearnersGuild/learning-os-software/issues/76

**Comment by jeffreywescott** [comment]
@tannerwelsh -- please see my updated issue description and make mods as needed.

**Comment by tannerwelsh** [comment]
Looks great @jeffreywescott, thanks! I can spell out more help/error text when needed too.

**Comment by jeffreywescott** [comment]
@tannerwelsh It would be great to get any error text captured here ASAP so we can avoid another round-trip of spec / implementation.

**Comment by tannerwelsh** [comment]
@jeffreywescott will do. I've got some bandwidth this morning.

**Comment by jeffreywescott** [comment]
:+1:

**Comment by tannerwelsh** [comment]
Updated description based on guide content produced in LearnersGuild/learning-os-software#120

**Comment by bundacia** [comment]
Closing this ticket and creating a ticket for the UI polish that got left out in the first pass: https://github.com/LearnersGuild/game-cli/issues/42
