### ISSUE TITLE
low-level errors should not be returned to the user

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/game-cli#28]
Things like:
- GraphQL parsing errors
- RethinkDB low-level errors

**Comment by bundacia** [comment]
@prattsj should we move this into the Error Refactoring epic?

**Comment by prattsj** [comment]
@bundacia: sure. i expect that since this isn't actually a standalone service, the error handling work done in `game` should prevent these kinds of errors from bubbling all the way out to `game-cli` in the first place. still, there's probably something worth taking a look at here.

**Comment by prattsj** [comment]
maybe @jeffreywescott can do this. i don't seem to have the ability to add it to any epics.

**Comment by bundacia** [comment]
Done.

**Comment by jeffreywescott** [comment]
This got addressed as part of https://github.com/LearnersGuild/game/pull/631
