### ISSUE TITLE
add `log` command descriptor

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/game-cli#3]
See also: [rocketchat-lg-slash-commands/#27](https://github.com/LearnersGuild/rocketchat-lg-slash-commands/issues/27)

**Comment by jeffreywescott** [comment]
Also, if the `log` command is _only_ for retrospectives, then perhaps it doesn't need subcommands at all. In which case, `log` by itself (without any arguments) could serve the purpose that `log retro` was meant to serve.

**Comment by bundacia** [comment]
last I heard from @tannerwelsh the argument for not naming this command `/retro` was that it was intended to be used for more types of feedback throughout the cycle, not just during the retro
