### ISSUE TITLE
`/project list`: Players can list projects that have been or need to be reviewed

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/game-cli#31]
Players can list all of the projects for the current cycle, including information about whether or not they've reviewed by the player:

### Command Examples

- `/project list`: list all projects for the current cycle
- `/project list -r`: list all projects for the current cycle that are currently in review
- `/project list --in-review`: list all projects for the current cycle that are currently in review (long form option)

### Example Output

```
@learner  > /project list
@echo     > There are 5 projects active this cycle.
            You have completed 3 projects thus far. Your current project is in review.

            Run `/project list -r` to list projects in review.

@learner  > /project list --in-review
@echo     > You have reviewed 2/5 projects this cycle. Nice work!

               Project                  C    Q    Artifact
            X  #terrible-tiger          63   42   https://github.com/owner/repo
            X  #anxious-aardvark        19   77   https://github.com/owner/repo
            -  #silly-slug                        https://github.com/owner/repo
            -  #fantastic-falcon                  https://github.com/owner/repo
            -  #creepy-caterpillar                https://github.com/owner/repo
```

Related: #27, #33

**Comment by jeffreywescott** [comment]
@tannerwelsh -- please review this issue description and make mods as necessary.

**Comment by tannerwelsh** [comment]
Updated the description to change the flags a bit. Seems like `/project list --completed` should show me _projects_ I've completed, not the _reviews_.

To list the reviews I've given, I would expect that to be `/review list --completed` or something along those lines. Not critical for `v0`. So long players can see the list of projects up for review along with whether and how they've reviewed them.

Note: the `--completed` flag can be pushed to `v1` if necessary. Also not critical, just outlined here to distinguish between previous incarnation.

**Comment by jeffreywescott** [comment]
Moved the completed stuff to https://github.com/LearnersGuild/game-cli/issues/33

**Comment by tannerwelsh** [comment]
Updated description based on guide content produced in LearnersGuild/learning-os-software#120

**Comment by bundacia** [comment]
@tannerwelsh, @jeffreywescott: it seems strange to me that `/project list` doesn't actually list any projects. Am I reading that right? 

Also curious how we determine if a project is finished or not. Does the team manually mark it as complete? Or are we scraping some project duration value from the github issue and doing the math?

**Comment by bundacia** [comment]
Oh, or do we consider it complete once there's an artifact URL?

**Comment by jeffreywescott** [comment]
Yes, you're reading the `/project list` correctly -- we're future-proofing it to (eventually) support things like listing the projects that the player in question has completed themselves, e.g. `--completed`.

It seems to me that if we're in the `REFLECTION` state for a cycle, any project associated with that cycle is now "fair game" to review. We may want to send a "nag" to players on teams who haven't yet set their artifact-url once we enter the `REFLECTION` state.

**Comment by bundacia** [comment]
Ok, so a single project could be reviewed multiple times by the same person, once every cycle. I guess it makes sense to let people review projects in progress, not just at the end.

**Comment by jeffreywescott** [comment]
Yeah. It would be interesting data to compare the quality of the code on a single project across cycles, too.

**Comment by jeffreywescott** [comment]
Okay, @tannerwelsh, @bundacia and I just spoke again about this, and there are some things about it that are still weird. Specifically, the way you've written-up the UX sort of hints-at or implies that projects have a state, and they _don't_, really.

Assumptions:
- (not for `v0`, but in the schema / design) projects may span multiple cycles
  - if a project spans multiple cycles, the project team _may_ change from cycle-to-cycle
- cycles have a state, like: `GOAL_SELECTION`, `PRACTICE`, `REFLECTION`, or `COMPLETE`
- a project doesn't really have a state
  - a project is considered complete if all of the cycles it is associated with are in the `COMPLETE` state
  - a project is either complete or active -- there's not really a way for a project to be "in review"

So -- questions:

1. Do we really want to use this `--in-review` option and "in review" language? There's functionally no difference between "in review" and "active".
2. Should projects be reviewed _every cycle_, even if they are only part-way through. For example, if a project spans 4 cycles, and it's 1 cycle in, should it be reviewed? (It would seem so, since the team may change and we may eventually want to associate the scores [quality, completeness] with those team members, right?)

**Comment by bundacia** [comment]
@jeffreywescott, @tannerwelsh: I suggest we hold this back for week 1. Players can see the status of a review using the `/review #project` command and the first week there will only be a handful of projects, so the moderator can easily remind everyone what they are in the chapter channel at review time.

I think there are more important things to focus on.

**Comment by bundacia** [comment]
By "hold back" I mean "let's wait to implement this until after the 15th."

**Comment by jeffreywescott** [comment]
@bundacia -- is there something below this in the "To-Do" lane that you think is more important (aside from the improved retro stuff)?

**Comment by jeffreywescott** [comment]
See also: https://github.com/LearnersGuild/los/issues/24

**Comment by jeffreywescott** [comment]
Related: https://github.com/LearnersGuild/los/issues/39

**Comment by jeffreywescott** [comment]
```javascript
r.db('game_development')
  .table('projects')
  .map(function (proj) {
    return proj.merge({
      completedBy: r.db('game_development')
    		.table('surveys')
        .get(proj('cycleHistory').nth(-1)('projectReviewSurveyId'))('completedBy')
    }).pluck('name', 'artifactURL', 'completedBy')
  })
```
