### ISSUE TITLE
When there is no cycle in GOAL_SELECTION, don't show voting panel

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/game-cli#34]
If the current cycle is not in `GOAL_SELECTION` state, then respond to `/vote` commands with the following message:

```
@echo > Voting is closed for the current cycle. When the moderator starts the next cycle, you will be able to vote on goals.
```

**Comment by jeffreywescott** [comment]
Tracked here: https://app.clubhouse.io/learnersguild/story/412/when-there-is-no-cycle-in-goal-selection-don-t-show-voting-panel
