### ISSUE TITLE
`/cycle` with no args should behave consistently with other commands

### ISSUE THREAD

**Issue by bundacia** [LearnersGuild/game-cli#37]
`/cycle` with no args prints a helpful help message, but `/log` just complains without telling me what my options are. The message it gives me is redundant as well.

![lxjos0cvxr](https://cloud.githubusercontent.com/assets/189699/16315970/57f8a3a2-3952-11e6-860e-bf842f468db5.gif)

@tannerwelsh what's the proper behavior? We should be consistent. (OND: I prefer the behavior of `/cycle`)

**Comment by jeffreywescott** [comment]
I prefer the latter -- we shouldn't print help unless people _ask_ us to print help.

**Comment by bundacia** [comment]
Yeah, I can see @jeffreywescott's point. Also, some commands will actually **do** something when called with no args, so we wouldn't want to train people that that's how to see the help.

**Comment by jeffreywescott** [comment]
Updated title to match actual bug.
