### ISSUE TITLE
Remove duplicate "Try `--help` for usage." message in errors

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/game-cli#48]
Errors show the "Try `--help` for usage." message twice. They only need to display that message once.

**Comment by bundacia** [comment]
@tannerwelsh: do you remember the repro steps for this? It doesn't happen all the time.

**Comment by jeffreywescott** [comment]
This is my fault. It should be up to game-cli to do this, but `formatError` in rocketchat-lg-slash-commands also does it.

**Comment by jeffreywescott** [comment]
Issue moved to [LearnersGuild/rocketchat-lg-slash-commands #42](https://github.com/LearnersGuild/rocketchat-lg-slash-commands/issues/42) via [**ZenHub**](https://www.zenhub.com/)
