### ISSUE TITLE
Make errors generated by commands invisible to other players

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/game-cli#49]
Errors generated by commands should not be public, but only visible to the user who issued the command. For example, if `/cycle init` throws an error, only show the error to the moderator.

I.e. don't clutter the channel with errors that other learners don't care about and can't resolve.

**Comment by bundacia** [comment]
The tricky thing here is that the command succeeds in that the state of the cycle is changed, but then actions that are triggered by that state change, like forming teams or creating retrospective surveys, could fail. Maybe those types of async failures should be sent to all chapter moderators or something.

**Comment by tannerwelsh** [comment]
> those types of async failures should be sent to all chapter moderators or something

👍  (or even to all users who have more than basic learner permissions)

**Comment by bundacia** [comment]
Issue moved to [LearnersGuild/game #280](https://github.com/LearnersGuild/game/issues/280) via [**ZenHub**](https://www.zenhub.com/)
