### ISSUE TITLE
add an (`export`ed) function to validate the arguments that were parsed

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/game-cli#5]
For example, with `vote`, if _any_ positional parameters are passed, _exactly two_ should be passed.

**Comment by bundacia** [comment]
should we roll this into a single function that parses the results and tosses an error if they're invalid?

**Comment by jeffreywescott** [comment]
Yes, there should be one top-level thing that does `parse`, returns the `usage` if help was requested, and `throw`s an `Error` if the command-invocation is invalid.
