### ISSUE TITLE
Make UX for project formation process more clear

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/game-cli#51]
- After being assigned to a project, I should be told what the project name is _as well as_ the project's goal, goal number, and the team in the channel I'm currently in.
- The first message in a new project channels should mention and link to the goal.
- When joining a new project, I should see who else is on my team (or be told how to find them).

**Comment by jeffreywescott** [comment]
@bundacia -- I believe this has been addressed, no?

**Comment by bundacia** [comment]
yup. Fixed by https://github.com/LearnersGuild/game/pull/220

<img width="694" alt="rocket_chat" src="https://cloud.githubusercontent.com/assets/189699/16591224/0fb6e5aa-4298-11e6-88b7-20b724fc5cdc.png">
