### ISSUE TITLE
merge `new-retro` into `master`

### ISSUE THREAD

**Issue by bundacia** [LearnersGuild/game-cli#70]

**Comment by prattsj** [comment]
Is this necessary? Can the pull request just be the tracking issue?

**Comment by bundacia** [comment]
There is no PR for the new-retro branch in `game-cli` yet, though we could create one. Doesn't matter to me either way. Hopefully it won't matter either way by lunch tomorrow 😜

**Comment by jeffreywescott** [comment]
I agree -- these issues are silly. I'm sorry I created them.

**Comment by bundacia** [comment]
closed in favor of https://github.com/LearnersGuild/game-cli/pull/74
