### ISSUE TITLE
Improve usability of `/project list`

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/game-cli#77]
From @bundacia's comment https://github.com/LearnersGuild/game-cli/pull/76#issuecomment-235681477:

My suggestions (ONA) would be to:

A) Have `/project list` list projects by default, either those the player is currently working on, or all of the active projects in the chapter.

and/or

B) Change the -r flag to be short for --reviews or something more accurate instead of --in-review

**Comment by jeffreywescott** [comment]
Superceded by #85
