### ISSUE TITLE
moderators can determine how many times each player was an "advanced player" on a team

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/game-cli#83]
## Overview

As per https://github.com/LearnersGuild/game/issues/418, moderators need to be able to determine how many times each was assigned as an advanced player (a total from all previous cycles).

Related: https://github.com/LearnersGuild/game-cli/issues/82

## Command / Arguments

TBD

## Output to Moderator

TBD

## Player Visibility

TBD

**Comment by jeffreywescott** [comment]
## Open UX Issues

- How should the moderator make this determination? What command + arguments should be used?
- How is the information presented?
- Is this information public / private? In other words, can non-moderators "view" it somehow?

**Comment by prattsj** [comment]
@tannerwelsh @shereefb: talking with @bundacia now about time pressure and the plan to deliver out essential features for Sep. 19. Is this really an essential item? Given especially that it's still blocked by UX, we're wondering if this actually needs to be tagged for the v1 milestone or if we can remove it?

**Comment by prattsj** [comment]
also /cc @jeffreywescott - just noticing now that you added this to the v1 milestone :)

**Comment by jeffreywescott** [comment]
IIRC, this was added b/c with the new algorithm, the moderator will now be _choosing_ the advanced players, and we wanted to avoid choosing the same players over and over again.

I'm okay punting if @shereefb is.

**Comment by shereefb** [comment]
Yep it's to help me choose. 
If we're keeping track somewhere that I can query later that suffices for now.

**Comment by jeffreywescott** [comment]
Moved to v2 (beta).

**Comment by jeffreywescott** [comment]
Issue moved to [LearnersGuild/game-prototype #67](https://github.com/LearnersGuild/game-prototype/issues/67) via [**ZenHub**](https://www.zenhub.com/)
