### ISSUE TITLE
Change behavior of `/project list` command

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/game-cli#84]
Based on https://github.com/LearnersGuild/game/issues/431, `/project list -r` will no longer be used.

The `-r` flag is to be removed, and `/project list` will display all active projects, the handles of their team, and the artifact url.
### Example usage

```
@learner  > /project list
@echo     > There are 5 active projects.

            #terrible-tiger
            @billy, @bobby, @bud
            https://github.com/owner/repo

            #anxious-aardvark    
            @sally, @sarah, @sid
            https://github.com/owner/repo

            #silly-slug          
            @timmy, @tommy, @ted
            https://github.com/owner/repo

            #fantastic-falcon    
            @gabby, @gilly, @gaz
            https://github.com/owner/repo

            #creepy-caterpillar  
            @fanny, @fawn, @fred
            https://github.com/owner/repo
```
#### For `/project`

```
/project - manage projects

Usage:
    /project [options] <command>

Commands:
    list         - List all active projects.

    set-artifact - Set the artifact for a project.



Options:
    --help, -h            print usage information


Examples:
    # List active projects, including team and artifact information
    /project list

    # Set the artifact for the #bad-lemurs-12 project.
    /project set-artifact #bad-lemurs-12 https://github.com/reactjs/redux
```
#### For `/project list` subcommand

```
/project list - show active projects along with their team and artifact

Usage:
    /project list [options]

Options:
    --help, -h            print usage information
```

**Comment by jeffreywescott** [comment]
@tannerwelsh this looks great, although I think displaying team members inline like you suggest is going to cause very awkward formatting, since sometimes teams are as many as 5 people and handles are as long as 13-14 characters. It's going to make it really hard to read, and the columns won't line up.

**Comment by tannerwelsh** [comment]
Good point @jeffreywescott. Just changed the output to make the project data multi-row instead of multi-column. Should reduce the total width of output, and make it more readable.

Omitting labels because the formatting of each line provides needed context to understand what it refers to (e.g. `#` for project name), and having a black line between projects creates an unambiguous separation.

**Comment by jeffreywescott** [comment]
Admin UI to the rescue!
