### ISSUE TITLE
Update `/review` to do the job of former `/project list -r`

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/game-cli#85]
Based on changes in https://github.com/LearnersGuild/game/issues/431, `/project list -r` is being removed. This leaves the use case of "Players can see which projects they've reviewed, what their scores were, and which are available for review" unaddressed.

To address this gap, we'll add a `list` subcommand to `/review` that responds with the same content that `/project list -r` used to.

Then, because `list` doesn't take the same options as regular `/review` command, the default behavior for `/review` will be moved to a `submit` subcommand.
### Example usage

```
@learner  > /review list
@echo     > You have reviewed 2/5 projects this cycle. Nice work!

               Project                  C    Q    Artifact
            X  #terrible-tiger          63   42   https://github.com/owner/repo
            X  #anxious-aardvark        19   77   https://github.com/owner/repo
            -  #silly-slug                        https://github.com/owner/repo
            -  #fantastic-falcon                  https://github.com/owner/repo
            -  #creepy-caterpillar                https://github.com/owner/repo

@learner  > /review submit #fantastic-falcon
@echo     > [same thing as what `/review #fantastic-falcon` does currently]

@learner  > /review
@echo     > Invalid arguments. Try --help for usage.
```
#### For `/review`

```
/review - provide feedback on a project

Usage:
    /review [options]

Commands:
    list         - Show project reviews
    submit       - Submit project review

Options:
    --help, -h            print usage information

Examples:
    # Show projects you've reviewed
    /review list

    # Show review status and artifact URL for the fantastic-falcon project.
    /review submit #fantastic-falcon

    # Rate the completeness and quality of the fantastic-falcon project.
    /review submit #fantastic-falcon --completeness 89 --quality 93
```
#### For `/review list` subcommand

```
/review list - show reviewed projects

Usage:
    /review list [options]

Options:
    --help, -h            print usage information
```
#### For `/review submit` subcommand

```
/review submit - submit a project review

Usage:
    /review submit [options] <project>

Options:
    --completeness, -c    A score between 1-100 indicating how complete you
                          believe the project is.

    --quality, -q         A score between 1-100 indicating your perception of
                          the quality of this project.

    --help, -h            print usage information
```

**Comment by jeffreywescott** [comment]
@tannerwelsh, this violates the consistency of the CLI, in my opinion, because the options (`-c` and `-q`) don't apply to all subcommands (in this case, `list`).

I'd suggest adding another subcommand for leaving a review, and applying the `-c` and `-q` options to it. Perhaps `/review submit` or `/review add`?

**Comment by tannerwelsh** [comment]
You're right @jeffreywescott, that's an oversight on my part. Will update the spec and help message.

**Comment by tannerwelsh** [comment]
updated spec and help message

**Comment by jeffreywescott** [comment]
Tracked here: https://app.clubhouse.io/learnersguild/story/415/update-review-to-do-the-job-of-former-project-list-r
